name: .NET Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage;Format=opencover" --logger trx  --results-directory ./TestResults

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
        
    - name: Generate HTML report
      run: reportgenerator -reports:"./TestResults/*/coverage.opencover.xml" -targetdir:"./TestResults/CoverageReport" -reporttypes:Html

    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: "Code coverage report"
        path: ./TestResults/CoverageReport
